In [1]:
import pandas as pd
df = pd.read_csv("weather_2024.csv")
df

,觀測時間(hour),測站氣壓(hPa),海平面氣壓(hPa),氣溫(℃),露點溫度(℃),相對溼度(%),風速(m/s),風向(360degree),最大瞬間風(m/s),最大瞬間風風向(360degree),降水量(mm),降水時數(h),日照時數(h),全天空日射量(MJ/㎡),能見度(km),紫外線指數,總雲量(0~10),source_file
0,1,1017.4,1021.0,16.2,10.1,67,2.7,90,6.9,100,0.0,0.0,--,0.0,--,0,--,466920-2024-01-01.csv
1,2,1017.0,1020.6,16.5,10.6,68,3.6,90,8.3,70,0.0,0.0,--,0.0,--,0,--,466920-2024-01-01.csv
2,3,1016.6,1020.2,16.6,10.9,69,3.2,90,8.3,80,0.0,0.0,--,0.0,--,0,--,466920-2024-01-01.csv
3,4,1016.2,1019.8,16.5,11.2,71,2.8,90,8.4,80,0.0,0.0,--,0.0,--,0,--,466920-2024-01-01.csv
4,5,1016.1,1019.7,16.5,11.5,72,2.9,80,8.0,90,0.0,0.0,--,0.0,--,0,--,466920-2024-01-01.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,20,1015.3,1018.9,16.4,15.3,93,2.8,100,7.9,90,0.5,0.7,--,0.0,NaN,0,NaN,466920-2024-12-31.csv
8780,21,1015.2,1018.8,16.3,15.5,95,2.9,100,6.1,90,2.0,1.0,--,0.0,NaN,0,NaN,466920-2024-12-31.csv
8781,22,1015.3,1018.9,16.4,15.8,96,2.1,130,7.6,80,2.5,1.0,--,0.0,NaN,0,NaN,466920-2024-12-31.csv
8782,23,1014.9,1018.5,16.6,16.0,96,1.5,110,5.0,160,1.5,0.9,--,0.0,NaN,0,NaN,466920-2024-12-31.csv
8783,24,1014.7,1018.3,16.6,16.0,96,1.6,90,5.0,80,0.5,0.8,--,0.0,NaN,0,NaN,466920-2024-12-31.csv

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   觀測時間(hour)          8784 non-null   int64
 1   測站氣壓(hPa)           8784 non-null   object
 2   海平面氣壓(hPa)          8784 non-null   object
 3   氣溫(℃)               8784 non-null   object
 4   露點溫度(℃)             8784 non-null   object
 5   相對溼度(%)             8784 non-null   object
 6   風速(m/s)             8784 non-null   object
 7   風向(360degree)       8784 non-null   object
 8   最大瞬間風(m/s)          8784 non-null   float64
 9   最大瞬間風風向(360degree)  8784 non-null   int64
 10  降水量(mm)             8784 non-null   object
 11  降水時數(h)             8784 non-null   object
 12  日照時數(h)             8784 non-null   object
 13  全天空日射量(MJ/㎡)        8784 non-null   float64
 14  能見度(km)             8760 non-null   object
 15  紫外線指數               8784 non-null   object
 16  總雲量(0~10)           8760 non-null   object
 17  source_file         8784 non-null   object
dtypes: float64(2), int64(2), object(14)
memory usage: 1.2+ MB

In [12]:
def take_date(str):
    parts = str.split("-")
    raw = "-".join(parts[1:])
    date = raw.split(".")[0]
    return date

df['日期'] = df['source_file'].apply(take_date)
df.head()

,觀測時間(hour),測站氣壓(hPa),海平面氣壓(hPa),氣溫(℃),露點溫度(℃),相對溼度(%),風速(m/s),風向(360degree),最大瞬間風(m/s),最大瞬間風風向(360degree),降水量(mm),降水時數(h),日照時數(h),全天空日射量(MJ/㎡),能見度(km),紫外線指數,總雲量(0~10),source_file,日期
0,1,1017.4,1021.0,16.2,10.1,67,2.7,90,6.9,100,0.0,0.0,--,0.0,--,0,--,466920-2024-01-01.csv,2024-01-01
1,2,1017.0,1020.6,16.5,10.6,68,3.6,90,8.3,70,0.0,0.0,--,0.0,--,0,--,466920-2024-01-01.csv,2024-01-01
2,3,1016.6,1020.2,16.6,10.9,69,3.2,90,8.3,80,0.0,0.0,--,0.0,--,0,--,466920-2024-01-01.csv,2024-01-01
3,4,1016.2,1019.8,16.5,11.2,71,2.8,90,8.4,80,0.0,0.0,--,0.0,--,0,--,466920-2024-01-01.csv,2024-01-01
4,5,1016.1,1019.7,16.5,11.5,72,2.9,80,8.0,90,0.0,0.0,--,0.0,--,0,--,466920-2024-01-01.csv,2024-01-01

In [14]:
df = df.drop(columns='source_file')
df.head()

,觀測時間(hour),測站氣壓(hPa),海平面氣壓(hPa),氣溫(℃),露點溫度(℃),相對溼度(%),風速(m/s),風向(360degree),最大瞬間風(m/s),最大瞬間風風向(360degree),降水量(mm),降水時數(h),日照時數(h),全天空日射量(MJ/㎡),能見度(km),紫外線指數,總雲量(0~10),日期
0,1,1017.4,1021.0,16.2,10.1,67,2.7,90,6.9,100,0.0,0.0,--,0.0,--,0,--,2024-01-01
1,2,1017.0,1020.6,16.5,10.6,68,3.6,90,8.3,70,0.0,0.0,--,0.0,--,0,--,2024-01-01
2,3,1016.6,1020.2,16.6,10.9,69,3.2,90,8.3,80,0.0,0.0,--,0.0,--,0,--,2024-01-01
3,4,1016.2,1019.8,16.5,11.2,71,2.8,90,8.4,80,0.0,0.0,--,0.0,--,0,--,2024-01-01
4,5,1016.1,1019.7,16.5,11.5,72,2.9,80,8.0,90,0.0,0.0,--,0.0,--,0,--,2024-01-01